TITLE = "Password Generator"
THEME = "system"
WINDOW_WIDTH = WINDOW_MAX_WIDTH = 500
WINDOW_HEIGHT = WINDOW_MAX_HEIGHT = 600
WINDOW_MIN_WIDTH = 300
WINDOW_MIN_HEIGHT = 400
IS_WINDOW_RESIZABLE = True
RUSSIAN_LETTERS = "абвгдеёжзийклмнопрстуфхцчшщъыьэюя"
ENGLISH_LETTERS = "abcdefghijklmnopqrstuvwqyz"
SPECIAL_SYMBOLS = "!@-=+/?<>,._`~"
NUMBERS = "0123456789"
MAX_LENGTH_OF_LENGTH = 2
TEXT_SIZE = 300
